/*
 * Create necessary objects
 */
CREATE TABLE public.widget_prices (
	record_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	widget_id int NULL ,
	price float4 NULL
);

CREATE TABLE public.widgets (
	record_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	description TEXT NOT NULL
);

INSERT INTO public.widgets (description) VALUES
	('Widget1'),
	('Widget2'),
	('Widget3');

CREATE TABLE public.widget_references (
	widget_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	reference TEXT NULL
);


CREATE VIEW public.current_prices
AS
SELECT widget_id, price, description
FROM widgets w
	INNER JOIN widget_prices wp ON w.record_id = wp.widget_id;


CREATE OR REPLACE FUNCTION public.get_all_widgets()
RETURNS TABLE (record_id int, description text)
AS 
$$
	SELECT record_id,
           description 
	FROM widgets
$$
LANGUAGE 'sql';