-- Script generated by Redgate Compare v1.15.2.10618
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.product_tags_tag_id_seq...';END$$;
ALTER SEQUENCE public.product_tags_tag_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.auto_test_tag_id_seq...';END$$;
ALTER SEQUENCE public.auto_test_tag_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts_view...';END$$;
DROP VIEW public.accounts_view;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.product_tags...';END$$;
DROP TABLE public.product_tags;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.auto_test...';END$$;
DROP TABLE public.auto_test;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.product_tags_tag_id_seq...';END$$;
DROP SEQUENCE public.product_tags_tag_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.auto_test_tag_id_seq...';END$$;
DROP SEQUENCE public.auto_test_tag_id_seq;

SET check_function_bodies = true;
