-- Script generated by Redgate Compare v1.19.6.13134
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.get_all_widgets()...';END$$;
DROP FUNCTION public.get_all_widgets();


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.get_all_widgets()...';END$$;
CREATE FUNCTION public.get_all_widgets()
RETURNS TABLE(record_id integer, description text, price real)
LANGUAGE sql
AS $_$
	SELECT w.record_id,
           w.description,
           wp.price
	FROM widgets w INNER JOIN widget_prices wp 
	ON wp.record_id = w.record_id

$_$;
ALTER FUNCTION public.get_all_widgets() OWNER TO postgres;

SET check_function_bodies = true;
