-- Script generated by Redgate Compare v1.15.2.10618
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.accounts_view...';END$$;
CREATE VIEW public.accounts_view (username, password) AS SELECT accounts.username,
    accounts.password
   FROM public.accounts;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.product_tags_tag_id_seq...';END$$;
CREATE SEQUENCE public.product_tags_tag_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.product_tags...';END$$;
CREATE TABLE public.product_tags (
    product_id integer NOT NULL,
    tag_id integer NOT NULL DEFAULT nextval('public.product_tags_tag_id_seq'::regclass),
    production_date character varying(20),
    tag_peni character varying(20),
    item_number character varying(20)
);
ALTER TABLE public.product_tags ADD CONSTRAINT product_tags_pkey PRIMARY KEY (product_id, tag_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.product_tags_tag_id_seq...';END$$;
ALTER SEQUENCE public.product_tags_tag_id_seq OWNED BY public.product_tags.tag_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.auto_test_tag_id_seq...';END$$;
CREATE SEQUENCE public.auto_test_tag_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.auto_test...';END$$;
CREATE TABLE public.auto_test (
    product_id integer NOT NULL,
    tag_id integer NOT NULL DEFAULT nextval('public.auto_test_tag_id_seq'::regclass),
    production_date character varying(20),
    tag_peni character varying(20),
    item_number character varying(20)
);
ALTER TABLE public.auto_test ADD CONSTRAINT auto_test_pkey PRIMARY KEY (product_id, tag_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.auto_test_tag_id_seq...';END$$;
ALTER SEQUENCE public.auto_test_tag_id_seq OWNED BY public.auto_test.tag_id;

SET check_function_bodies = true;
